import { Database } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { MediaResult, UploadMetadata, UploadStage } from "@/hooks/useUpload";

const formatBytes = (bytes?: number) => {
  if (!bytes) return "—";
  const sizes = ["Bytes", "KB", "MB", "GB"];
  const index = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, index)).toFixed(2)} ${sizes[index]}`;
};

const formatTime = (value?: string) => {
  if (!value) return "—";
  return new Intl.DateTimeFormat("en", {
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
  }).format(new Date(value));
};

export function MetadataCard({
  metadata,
  fileName,
  fileSize,
  stage,
  progressLabel,
}: {
  metadata: UploadMetadata | MediaResult | null;
  fileName?: string;
  fileSize?: number;
  stage: UploadStage;
  progressLabel: string;
}) {
  const status = stage === "complete" ? "PROCESSING REQUEST SENT" : progressLabel.toUpperCase();

  const metadataKey = "key" in (metadata || {})
    ? (metadata as UploadMetadata).key
    : (metadata as MediaResult | null)?.objectKey;

  const metadataFileName = "fileName" in (metadata || {})
    ? (metadata as UploadMetadata).fileName
    : (metadata as MediaResult | null)?.originalFileName;

  const metadataFileSize = metadata && "fileSize" in metadata
    ? metadata.fileSize
    : undefined;

  const metadataUploadedAt = metadata?.uploadedAt || (metadata as MediaResult | null)?.processedAt;

  const metadataStatus = (metadata as MediaResult | null)?.status || status;

  return (
    <Card className="rounded-2xl border-white/10 bg-[#0d131c] text-white shadow-2xl shadow-black/20">
      <CardHeader className="flex flex-row items-start gap-4 space-y-0">
        <div className="rounded-xl border border-amber-400/30 bg-amber-400/10 p-3 text-amber-300">
          <Database className="h-5 w-5" />
        </div>
        <div>
          <CardTitle className="text-xl">Image Metadata</CardTitle>
          <p className="text-sm text-slate-400">
            Upload details generated by MandVision
          </p>
        </div>
      </CardHeader>

      <CardContent>
        <dl className="space-y-4 text-sm">
          <MetadataRow label="File ID" value={metadata?.fileId || "—"} />
          <MetadataRow label="S3 Object Key" value={metadataKey || "—"} />
          <MetadataRow label="Original File Name" value={metadataFileName || fileName || "—"} />
          <MetadataRow label="File Size" value={formatBytes(metadataFileSize ?? fileSize)} />
          <MetadataRow label="Uploaded At" value={formatTime(metadataUploadedAt)} />
          <MetadataRow label="Status" value={metadataStatus} badge />
        </dl>
      </CardContent>
    </Card>
  );
}

function MetadataRow({
  label,
  value,
  badge = false,
}: {
  label: string;
  value: string;
  badge?: boolean;
}) {
  return (
    <div className="grid grid-cols-[150px_1fr] gap-4 border-b border-white/5 pb-3 last:border-0">
      <dt className="text-slate-400">{label}</dt>
      <dd className="min-w-0 text-right text-slate-100">
        {badge ? (
          <Badge className="border border-emerald-400/30 bg-emerald-400/10 text-emerald-300 hover:bg-emerald-400/10">
            {value}
          </Badge>
        ) : (
          <span className="break-words">{value}</span>
        )}
      </dd>
    </div>
  );
}